title: Taco Time Jackson Heights
author: Allen McLain
email: allenmclain417@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 - I love Tacos
 - I love Jackson Heights
 - Both of my loves in one spot

# social links
twitter_username: darthallen417
github_username:  allenmclain417

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
